### ISSUE TITLE
Info of the code

### ISSUE THREAD

**Issue by FrancescoArcuri13** [sefcom/Witcher#14]
Is it possible to get a description of the code architecture?
Where are the results output? 
How can the results be consulted what format do they have?

**Comment by FrancescoArcuri13** [comment]
Once I run the test how can I view the results what are the references?

**Comment by adamdoupe** [comment]
Hi @FrancescoArcuri13 . This is a research project, and it’s not under active development. You will need to read the code to figure out the answers to these questions.

If you would like to submit a PR with documentation, we would be happy to include it.
